config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "admin#index"

  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"
  get "account", to: "users#edit"
  put "account", to: "users#update"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "change_password", to: "passwords#change"
  post "change_password", to: "passwords#change"


  get "unsubscribe/:id", to: "unsubscribe#show"
  put "unsubscribe/:id", to: "unsubscribe#update"

  mount MissionControl::Jobs::Engine => "/jobs"

  resources :users

  resources :confirmations, only: [ :create, :edit, :new ], param: :confirmation_token
  resources :passwords, only: [ :create, :edit, :new, :update ], param: :password_reset_token

  resource :fee, only: [ :show, :edit, :update ]

  resources :quickbooks do
    collection do
      get :connect             # This starts the OAuth flow
      get :new, as: :callback  # This is where Intuit sends the user back
      get :invoices
      post :generate_invoices
    end
  end

  resources :roles, except: [ :new, :destroy ] do
    resources :users do
      member do
        delete :rmrole
      end
    end
  end

  resources :moorings, only: [ :index ] do
    collection do
      get :unassigned
    end
  end

  resources :drysails, only: [ :index, :update ] do
    member do
      get :assign
    end
  end

  resources :memberships do
    collection do
      get :list
      get :labels
      post :download_labels
      get :spreadsheets
      post :download_spreadsheet
      get :initiation_report
      post :assign_drysail
      post :add_person
    end
    member do
      get :wl
      post :wladd
      get :associate
      patch :save_association
      post :unassign
      post :unassign_drysail
    end
    resources :people
    resources :boats do
      member do
        delete :rmboat
      end
    end
   end

  resources :people, only: [ :destroy ]

  resources :committees, only: [] do
    collection do
      get :select
      get :list
      get :download_all
    end
    member do
      get :download
    end
  end

  resources :boats do
    member do
      get :associate
      patch :save_association
    end
  end

  resources :wait_list_entries, except: [ :show ] do
    member do
      get :assign
      patch :mooring_update
    end
  end

  resources :mailings do
    member do
      post :send_email
    end
  end
  resource :log_info_email, only: [ :edit, :update ]
  get "subscription_list", to: "reports#subscription_list"

  resources :active_sessions, only: [ :index, :destroy ] do
    collection do
      delete "destroy_all"
    end
  end

  get "summary_report", to: "reports#summary"
  get "history_report", to: "reports#history"
  get "moorings_report", to: "reports#moorings"
  get "associates_report", to: "reports#associates"
  get "shrink_image/:id", to: "image#shrink", as: "shrink"
end

app/controllers/memberships_controller.rb
require "prawn"
require "prawn/measurement_extensions"

class MembershipsController < ApplicationController
  helper_method :sort_column, :sort_direction, :mooring_sort_column

  def index
    @status_options = %w[Accepted Active Associate Honorary Inactive Life Resigned Senior]
    params[:status] ||= [ "Active", "Associate", "Honorary", "Life", "Senior" ]
    @memberships = filter_memberships(params)
    @memberships = @memberships.order(sort_column + " " + sort_direction)
    @lastname = params[:lastname]
    @selected_status = params[:status]
    @operator = params[:operator]
    @since = params[:since]
  end

  def new
    @membership = Membership.new
    @membership.people << Person.new
    @membership.application_date = Time.now
  end

  def create
    @membership = Membership.new(membership_params)
    if @membership.save
      flash[:success] = "Membership was successfully created."
      redirect_to wl_membership_path(@membership)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def wl
    @membership = Membership.find(params[:id])
  end

  def wladd
    @membership = Membership.find(params[:id])
    @wl = WaitListEntry.new
    @wl.membership = @membership
    @wl.date = @membership.application_date
    @wl.save
    redirect_to membership_path(@membership)
  end

  def show
    set_filter_params
    set_back_path
    @membership = Membership.find(params[:id])
    @membership.people.sort
  end

  def edit
    @membership = Membership.includes(:people, :boats, :initiation_installments).find(params[:id])
  end

  def update
    @membership = Membership.includes(:people, :boats, :initiation_installments).find(params[:id])
    current_status = @membership.Status
    @membership.attributes = membership_params
    @membership.change_status_date = Time.now.strftime("%Y-%m-%d") if current_status != @membership.Status
    @membership.resignation_date = Time.now.strftime("%Y-%m-%d") if @membership.Status == "Resigned" && @membership.resignation_date.nil?
    if (current_status == "Inactive") && (@membership.Status == "Active")
      flash[:alert] = "For members returning to Active status from Inactive status, if adding to the waitlist, the waitlist date should be the day payment is received for the return to Active."
    end
    unless @membership.mooring_eligible
      flash[:alert] = "Mooring removed due to membership category update." if !@membership.mooring.nil?
      @membership.mooring = nil
      @membership.remove_boat_from_mooring
    end
    unless @membership.wait_list_eligible
      flash[:alert] = "Member removed from wait list due to membership category update." if !@membership.wait_list_entry.nil?
      @membership.wait_list_entry = nil
    end
    if @membership.save
      flash.delete(:alert) if flash[:alert].blank?
      flash[:success] = "Membership was successfully updated."
      @membership.check_mooring
      @membership.check_drysail
      redirect_to membership_path(@membership)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @membership = Membership.find(params[:id])
    @membership.destroy
    flash[:success] = "Membership was successfully deleted."
    redirect_to memberships_path(since: session[:since],
                                 operator: session[:operator],
                                 lastname: session[:lastname],
                                 status: session[:status],
                                 sort: session[:sort],
                                 direction: session[:direction])
  end

  def associate
    @membership = Membership.find(params[:id])
    @boats = Boat.order(:Name) - @membership.boats
  end

  def save_association
    @membership = Membership.find(params[:id])
    @boat = Boat.find(params[:membership][:boats])
    @membership.boats << @boat
    @membership.mooring = @boat.mooring if @boat.location == "Mooring"
    if @membership.save
      flash[:notice] = "Saved association."
      redirect_to membership_path(@membership)
    else
      # :nocov:
      @boats = Boat.order(:Name) - @membership.boats
      flash[:alert] = "Error saving association."
      render :associate, status: :unprocessable_entity
      # :nocov:
    end
  end

  def unassign
    @membership = Membership.find(params[:id])
    mooring_id = @membership.mooring_id
    @membership.mooring = nil
    @membership.remove_boat_from_mooring
    if @membership.save
      flash[:notice] = "Mooring ##{mooring_id} unassigned."
    else
      # :nocov:
      flash[:alert] = "Problem unassigning mooring ##{mooring_id}."
      # :nocov:
    end
    redirect_to moorings_path
  end

  def unassign_drysail
    @membership = Membership.find(params[:id])
    drysail = @membership.drysail
    @membership.remove_boat_from_drysail
    @membership.drysail = nil
    if @membership.save
      flash[:notice] = "Dry sail spot ##{drysail.id} unassigned."
    else
      # :nocov:
      flash[:alert] = "Problem unassigning dry sail spot ##{drysail.id}."
      # :nocov:
    end
    redirect_to drysails_path
  end

  def labels
    @label_options = [ "All", "No Email", "Workday" ]
  end

  def download_labels
    workday = false
    case params[:labels]
    when "All"
      members = Membership.members
    when "No Email"
      members = Membership.mail_hardcopy
    when "Workday"
      members = Membership.all_active
      workday = true
    end
    send_data generate_labels(members, workday), filename: "labels.pdf", type: "application/pdf"
  end

  def spreadsheets
    @spreadsheet_options = [ "Billing", "Log Members", "Log Fleet",
      "Log Partner Xref", "Member Cards/Workday Checklist", "Evite", "Resigned", "Member List" ]
  end

  def download_spreadsheet
    Membership.reset_flash_message
    export_csv(params[:spreadsheet])
  end

  def initiation_report
    installments = InitiationInstallment.includes(:membership).order(:year)
    @initiation_fee_due = []
    installments.each do |i|
      next if i.membership.Status != "Active" && i.membership.Status != "Associate"
      @initiation_fee_due << [ i.membership, i.membership.Status, i.membership.MemberSince, i.membership.active_date, i.amount, i.year ]
    end
  end

  private

  def sort_column
    Membership.column_names.include?(params[:sort]) ? params[:sort] : "LastName"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def generate_labels(list, workday)
    pages = list.length / 30
    Prawn::Document.new(left_margin: 0.21975.in, right_margin: 0.21975.in) do |p|
      p.font "Times-Roman"
      p.font_size 11
      (0..pages).each do |page|
        p.define_grid(columns: 3, rows: 10, row_gutter: 0, column_gutter: 10)
        p.grid.rows.times do |i|
          p.grid.columns.times do |j|
            b = p.grid(i, j)
            indent = 10
            p.bounding_box [ b.top_left[0] + indent, b.top_left[1] ], width: b.width, height: b.height - indent do
              m = list[page * 30 + 3 * i + j]
              overflow = generate_text(p, m, b.width, workday) if !m.nil?
              logger.error "#{m.MailingName} overflowed: |#{overflow}|" if overflow && overflow != ""
            end
            # p.stroke do
            #  p.rectangle(b.top_left, b.width, b.height)
            # end
          end
        end
        p.start_new_page if page != pages
      end
    end.render
  end

  def generate_text(p, m, width, workday)
    if p.width_of(m.MailingName) > width # need to split mailing name
      if m.MailingName.index(" & ")
        sp = m.MailingName.split(" & ")
        mn = sp[0] + " &\n" + p.indent(5) { sp[1] }
      elsif m.MailingName.index(" and ")
        sp = m.MailingName.split(" and ")
        mn = sp[0] + " &\n" + p.indent(5) { sp[1] }
      else
        # truncate
        mn = m.MailingName.slice(0, width - 1)
      end
    else
      mn = m.MailingName
    end
    if p.width_of(m.StreetAddress) > width # need to split address
      sp = m.StreetAddress.split(",")
      ma = sp[0] + "\n" + "  #{sp[1]}"
    else
      ma = m.StreetAddress
    end
    if workday
      p.text m.LastName, style: :bold
      p.text "\n\n#{mn}"
    else
      p.text_box "#{mn}\n#{ma}\n#{m.City}, #{m.State}   #{m.Zip}", valign: :center
    end
  end

  def export_csv(type)
    mime_type = "text/csv"
    filename = I18n.l(Time.now, format: :short) + type.to_s
    filename += ".csv"

    content = if type.start_with?("Member Card")
                Person.to_csv
    elsif type.start_with?("Resigned")
                Person.resigned_to_csv
    elsif type.start_with?("Member List")
                Membership.list_to_csv
    elsif type.start_with?("Log Fleet")
                Boat.to_csv
    else # billing
                Membership.to_csv(type)
    end
    if Membership.flash_message != ""
      flash[:error] = "Error:\n #{Membership.flash_message}"
      redirect_to spreadsheets_memberships_path
    else
      send_data(content, type: mime_type, filename: filename)
    end
  end

  def filter_memberships(params)
    @memberships = Membership.all
    save_params
    @memberships = @memberships.since(params[:since], params[:operator]) if params[:since].present?
    @memberships = @memberships.lastname(params[:lastname]) if params[:lastname].present?
    @memberships = @memberships.status(params[:status]) if params[:status].present?
  end

  def membership_params
    params.require(:membership).permit(:LastName, :MailingName, :StreetAddress, :City,
      :State, :Zip, :Country, :Status, :MemberSince, :mooring,
      :application_date, :active_date, :resignation_date, :initiation,
      :paid, :skip_mooring, :prefer_partner_email, :installments, :initiation_fee, :drysail_num, :notes,
      people_attributes: Person.attribute_names.map(&:to_sym).push(:_destroy),
      boats_attributes: Boat.attribute_names.map(&:to_sym).push(:_destroy),

app/views/memberships/_boats_table.html.erb
<table class="table table-sm">
  <thead class="thead-light">
    <tr>
      <% if locals[:show_sort] %>
      <th><%= sortable "Name" %></th>
      <th><%= sortable "Mfg_Size", "Mfg/Size" %></th>
      <th><%= sortable "Type" %></th>
      <th><%= sortable "Length" %></th>
      <th><%= sortable "Draft" %></th>
      <th><%= sortable "mooring_id", "Mooring" %></th>
      <th><%= sortable "drysail_id", "Drysail" %></th>
      <% else %>
      <th>Name</th>
      <th>Mfg/Size</th>
      <th>Type</th>
      <th>Length</th>
      <th>Draft</th>
      <th>Mooring</th>
      <th>Drysail</th>
      <th></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% for boat in locals[:boats_array] %>
    <tr>
      <% if boat.Name.blank? %>
      <td><%= boat.Name %></td>
      <td><%= link_to boat.Mfg_Size, boat_path(boat) %></td>
      <% else %>
      <td><%= link_to boat.Name, boat_path(boat) %></td>
      <td><%= boat.Mfg_Size %></td>
      <% end %>
      <td><%= boat.Type %></td>
      <td><%= boat.Length %></td>
      <td><%= boat.Draft %></td>
      <td><%= boat.mooring_id %></td>
      <td><%= boat.drysail&.id %></td>
      <td class="list-actions">
	<%= link_to 'Delete', rmboat_membership_boat_path(locals[:membership], boat), data: { turbo_confirm: 'Are you sure?', turbo_method: :delete} %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/memberships/_form.html.erb
<%= form_with model: @membership, data: {controller: 'dynamic-form'} do |f| %>
    <template data-dynamic-form-target="installmentTemplate">
	<%= f.fields_for :initiation_installments, InitiationInstallment.new, child_index: 'NEW_RECORD' do |ii_fields| %>
	    <%= render "initiation_installment", f: ii_fields %>
	<% end %>
    </template>

    <template data-dynamic-form-target="personTemplate">
	<%= f.fields_for :people, Person.new, child_index: 'NEW_RECORD' do |person_fields| %>
	    <%= render "people/form", f: person_fields %>
	<% end %>
    </template>
    
    <template data-dynamic-form-target="boatTemplate">
      <%= f.fields_for :boats, Boat.new, child_index: 'NEW_RECORD' do |boat_fields| %>
	<%= render "boats/form", f: boat_fields, mooring: @membership.mooring&.id, drysail: @membership.drysail&.id %>
      <% end %>
    </template>
    
    <% if @membership.errors.any? %>
      <div id="error_explanation">
	<h3><%= @membership.errors.count %> errors prohibited this membership from being saved:</h3>
	<ul>
	  <% @membership.errors.full_messages.each do |message| %>
	    <li><%= message %></li>
	  <% end %>
	</ul>
      </div>
    <% end %>
    
    <%= render partial: "form_member_update1", locals: { f: f} %>
    <%= render partial: "form_membership_update", locals: { f: f} %>
    
    <h4>People</h4>
    <hr>
    <div id="people" class="ms-4" data-controller="child-hide">
	<%= f.fields_for :people do |person_fields| %>
	    <%= render "people/form", f: person_fields %>
	<% end %>
	
	<div data-dynamic-form-target="person"></div>
	<button type="button" data-action="dynamic-form#add_person", class="btn btn-primary mb-3">Add person</button>
    </div>
    
    <h4>Boat</h4>
    <hr>
    <div class="boat_fields ms-4">
	<%= f.fields_for :boats do |f| %>
	    <%= render 'boats/form', f: f, mooring: @membership.mooring&.id, drysail: @membership.drysail&.id  %>
	<% end %>
	<div data-dynamic-form-target="boat"></div>
	<button type="button" data-action="dynamic-form#add_boat", class="btn btn-primary mb-3">Add boat</button>
    </div>
    
    <div class="form-group row mt-4">
	<div class="mr-4">
	    <%= f.submit button, class: "btn btn-primary" %>
	    <% if button == "Update Membership" %>
		| <%= link_to 'Back', membership_url(@membership) %>
	    <% end %>
	</div> 
    </div>
<% end %>

app/views/memberships/_form_member_update1.html.erb
<div class="row mb-2">
    <div class="col-sm-4">
	<span class="has-float-label">
	    <%= f.text_field :LastName, id: "MembershipLastName", class: "form-control", placeholder: " " %>
	    <label for="LastName">Last Name</label>
	</span>
    </div>
    <div class="col-sm-8">
	<span class="has-float-label">
	    <%= f.text_field :MailingName, id: "MailingName", class: "form-control", placeholder: " " %>
	    <label for="MailingName">Mailing Name</label>
	</span>
    </div>
</div>
<div class="row mb-2">
    <div class="col-sm-4">
	<span class="has-float-label">
	    <%= f.text_field :StreetAddress, id: "StreetAddress", class: "form-control", placeholder: " " %>
	    <label for="StreetAddress">Street Address</label>
	</span>
    </div>
    <div class="col-sm-4">
	<span class="has-float-label">
	    <%= f.text_field :City, id: "City", class: "form-control", placeholder: " " %>
	    <label for="City">City</label>
	</span>
    </div>
</div>
<div class="row mb-2">
  <div class="col-sm-2">
    <span class="has-float-label">
      <%= f.text_field :State, id: "State", class: "form-control", placeholder: " " %>
      <label for="State">State</label>
    </span>
  </div>
  <div class="col-sm-2">
    <span class="has-float-label">
      <%= f.text_field :Zip, id: "Zip", class: "form-control", placeholder: " " %>
      <label for="Zip">Zip</label>
    </span>
  </div>
  <div class="col-sm-3">
    <span class="has-float-label">
      <%= f.text_field :Country, id: "Country", class: "form-control", placeholder: " " %>
      <label for="Country">Country</label>
    </span>
  </div>
</div>

app/views/memberships/_form_membership_update.html.erb
<div class="row">
    <div class="col-sm-2">
	<span class="has-float-label">
	    <%= f.text_field :MemberSince, id: "MemberSince", class: "form-control", placeholder: " " %>
	    <label for="MemberSince">Member Since</label>
	</span>
    </div>
    <label for="Status" class="col-form-label pt-0 col-auto">Status:</label>
    <div class="col-sm-2">
      <% if Current.user.roles?(%w(Admin Membership)) %>
	<%= f.collection_select :Status, Memberstatus.order(:Status), :Status, :Status, class: "form-control" %>
      <% else %>
	<%= @membership.Status %>
      <% end %>
    </div>
    <div class="col-sm-3">
      <p>Mooring #<%= @membership.mooring&.id %></p>
    </div>
    <div class="col-sm-3">
      <p>Dry Sail #<%= @membership.drysail&.id %></p>
    </div>
</div>

<% if Current.user.roles?(%w(Admin Membership Harbormaster)) %>
    <div class="row">
	<div class="col-sm-3">
	    <label for="application_date" class="col-form-label pt-0">Approval Date:</label>
	    <div class="">
	      <% if Current.user.roles?(%w(Admin Membership)) %>
	        <%= f.date_select :application_date, include_blank: true, order: [:month, :day, :year], start_year: 1960, end_year: Time.now.year, class: 'form-control' %>
	      <% else %>
	        <%= @membership.application_date %>
	      <% end %>
	    </div>
	</div>
	<div class="col-sm-3">
	    <label for="active_date" class="col-form-label pt-0">Active Date:</label>
	    <div class="">
	      <% if Current.user.roles?(%w(Admin Membership)) %>
  	        <%= f.date_select :active_date, include_blank: true, order: [:month, :day, :year], start_year: 1960, end_year: 1+Time.now.year, class: 'form-control' %>
	      <% else %>
	        <%= @membership.active_date %>	
	      <% end %>
	    </div>
	</div>
	<div class="col-sm-3">
	    <label for="resignation_date" class="col-form-label pt-0">Resignation_Date:</label>
	    <div class="">
	      <% if Current.user.roles?(%w(Admin Membership)) %>
	      <%= f.date_select :resignation_date, include_blank: true, order: [:month, :day, :year], start_year: Time.now.year-1, end_year: 1+Time.now.year, class: 'form-cont' %>
	      <% else %>
	      <%= @membership.resignation_date %>
	      <% end %>
	    </div>
	</div>
    </div>
    <div class="mb-4">
	<div class="form-check mr-4 mt-4">
	    <%= f.check_box :skip_mooring, class: "form-check-input" %>
	    <label for="skip_mooring" class="form-check-label">Skip mooring fee?</label>
	</div>
	<div class="form-check mr-4 mt-4">
	    <%= f.check_box :prefer_partner_email, class: "form-check-input" %>
	    <label for="prefer_partner_email" class="form-check-label">Prefer partner_email?</label>
	</div>
    </div>
    <div class="mb-3">
	<span class="has-float-label col-sm-12">
	    <%= f.text_area :notes, id: "notes", class: "form-control", placeholder: " " %>
	    <label for="notes">Notes</label>
	</span>
    </div>
    <% if Current.user.roles?(%w(Admin Membership)) %>
    <h5>Initiation Installments</h5>
    <hr>
    <div class="initiation_installment_fields ms-4">
	<%= f.fields_for :initiation_installments do |f| %>
	    <%= render 'initiation_installment', f: f %>
	<% end %>
	<div data-dynamic-form-target="installment"></div>
	<button type="button" data-action="dynamic-form#add_installment", class="btn btn-primary mb-3 mt-3">Add initiation installment</button>
    </div>
    <% end %>
<% end %>    

app/views/memberships/associate.html.erb
<h2>Associate boat with membership</h2>
<%= form_with model: @membership, url: save_association_membership_path do |f| %>
  <div class="form-row">
    <p><b>Membership: </b><%= @membership.MailingName %></p>
  </div>
  <div class="form-row">
    <label for="Boats" class="col-form-label pt-0">Boats:</label>
    <div class="col-sm-2">
      <%= f.collection_select(:boats, @boats, :id, :selection_string, class: "form-control") %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-3 pt-3">
      <%= f.submit "Associate", class: "btn btn-primary" %> | <%= link_to 'Back', membership_path(@membership) %>
    </div>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<h2 class="mb-3">Edit membership</h2>

<%= render partial: "form", locals: {button: "Update Membership"} %>

app/views/memberships/labels.html.erb
<h2>Generate Labels (Avery 5160)</h2>
<%= form_with url: download_labels_memberships_path, data: { turbo: false } do |f| %>
  <div class="row mb-3">
    <label class="col-auto col-form-label">Type:</label>
    <div class="col-sm-3">
      <%= f.select :labels, options_for_select(@label_options, @labels), {}, class: "form-control" %>
    </div>
  </div>
  <%= f.submit "Generate", class: "btn btn-primary" %> | <%= link_to 'Back', url_for(:back) %>
<% end %>

<p class="small mt-3">Note: When printing these labels, make sure "Page Scaling" is set to "None".</p>

app/views/memberships/show.html.erb
<div>
  <h3>Membership</h3>
  <hr>
  <table class="table table-sm">
    <tbody>
      <tr>
	<td><b>Last Name:</b></td><td><%= @membership.LastName %></td>
      </tr>
      <tr>
	<td><b>Mailing Name:</b></td><td><%= @membership.MailingName %></td>
      </tr>
      <tr>
	<td><b>Street Address:</b></td><td><%= @membership.StreetAddress %></td>
      </tr>
      <tr>
	<td><b>City:</b></td><td><%= @membership.City %></td>
      </tr>
      <tr>
	<td><b>State:</b></td><td><%= @membership.State %></td>
      </tr>
      <tr>
	<td><b>Zip:</b></td><td><%= @membership.Zip %></td>
      </tr>
      <tr>
	<td><b>Country:</b></td><td><%= @membership.Country %></td>
      </tr>
      <tr>
	<td><b>Mooring #:</b></td><td><%= @membership.mooring&.id %></td>
      </tr>
      <tr>
	<td><b>Dry Sail #:</b></td><td><%= @membership.drysail&.id %></td>
      </tr>
      <tr>
	<td><b>Member Since:</b></td><td><%= @membership.MemberSince %></td>
      </tr>
      <tr>
	<td><b>Status:</b></td><td><%= @membership.Status %></td>
      </tr>
      <tr>
	<td><b>Status Change Date:</b></td><td><%= @membership.change_status_date %></td>
      </tr>
      <tr>
	<td><b>Active Date:</b></td><td><%= @membership.active_date %></td>
      </tr>
      <tr>
	<td><b>Notes:</b></td><td><%= @membership.notes %></td>
      </tr>
    </tbody>
  </table>

  <% unless @membership.initiation_installments.empty? %>
  <h4>Initiation Installments</h4>
  <hr>
  <table class="table table-sm">
    <thead class="thead-light">
      <tr>
	<th>Year</th>
	<th>Amount</th>
      </tr>
    </thead>
    <tbody>
      <% for installment in @membership.initiation_installments %>
      <tr>
	<td><%= installment.year %></td>
	<td><%= installment.amount %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>

  <p>
    <%= link_to 'Edit Membership', edit_membership_path(@membership) %>
  </p>
  <% if not @membership.people.empty? %>
  <h3>People</h3>
  <hr>
  <table class="table table-sm">
    <thead class="thead-light">
      <tr>
	<th>First</th>
	<th>Last</th>
	<th>Type</th>
	<th>Home Phone</th>
	<th>Cell Phone</th>
	<th>Work Phone</th>
	<th>Email</th>
	<th>Committee</th>
	<th>BirthYear</th>
      </tr>
    </thead>
    <tbody>
      <% for person in @membership.people.sort %>
      <% hidden = person.MemberType == "Child" && ((Time.now.year - person&.BirthYear) > 23) %>
      <tr style="<%= hidden ? 'display:none' : '' %>">
	<td><%= person.FirstName %></td>
	<td><%= person.LastName %></td>
	<td><%= person.MemberType %></td>
	<td><%= person.HomePhone %></td>
	<td><%= person.CellPhone %></td>
	<td><%= person.WorkPhone %></td>
	<td><%= person.EmailAddress %></td>
	<td><%= person.Committee1 %></td>
	<td><%= person.BirthYear %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>
  <% if not @membership.boats.empty? %>
  <h3><%= 'Boat'.pluralize(@membership.boats.size) %></h3>
    <hr>
    <%= render 'boats_table', locals: {boats_array: @membership.boats, show_sort: false, membership: @membership.id } %>
  <% end %>
  <p>
    <%= link_to 'Associate an Existing Boat', associate_membership_path(@membership) %>
  </p>
  <p>
    <%= link_to 'Back', @back_path %>
  </p>
</div>

app/views/memberships/spreadsheets.html.erb
<h2>Generate a spreadsheet</h2>
<p>Note: these are tab separated files.</p>
<%= form_with url: download_spreadsheet_memberships_path, data: { turbo: false } do |f| %>
  <div class="row mb-2" >
    <label class="col-auto col-form-label">Type:</label>
    <div class="col-sm-3">
      <%= f.select :spreadsheet, options_for_select(@spreadsheet_options, @spreadsheet), {}, class: "form-control" %>
    </div>
  </div>
  <%= f.submit "Generate", class: "btn btn-primary" %> | <%= link_to 'Back', url_for(:back) %>
<% end %>

app/views/memberships/wl.html.erb
<div>
  <h2>Add <%= @membership.MailingName %> to waiting list?</h2>
  <%= form_with model: @membership, url: wladd_membership_path, html: {method: :post} do |f| %>
  <div class="form-group row">
    <div class="offset-sm-2 col-sm-10">
      <%= f.submit "Yes", class: "btn btn-primary" %> | <%= link_to "No", membership_path(@membership) %>
    </div>
  </div>
  <% end %>
</div>