config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "admin#index"

  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"
  get "account", to: "users#edit"
  put "account", to: "users#update"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "change_password", to: "passwords#change"
  post "change_password", to: "passwords#change"


  get "unsubscribe/:id", to: "unsubscribe#show"
  put "unsubscribe/:id", to: "unsubscribe#update"

  mount MissionControl::Jobs::Engine => "/jobs"

  resources :users

  resources :confirmations, only: [ :create, :edit, :new ], param: :confirmation_token
  resources :passwords, only: [ :create, :edit, :new, :update ], param: :password_reset_token

  resource :fee, only: [ :show, :edit, :update ]

  resources :quickbooks do
    collection do
      get :connect             # This starts the OAuth flow
      get :new, as: :callback  # This is where Intuit sends the user back
      get :invoices
      post :generate_invoices
    end
  end

  resources :roles, except: [ :new, :destroy ] do
    resources :users do
      member do
        delete :rmrole
      end
    end
  end

  resources :moorings, only: [ :index ] do
    collection do
      get :unassigned
    end
  end

  resources :drysails, only: [ :index, :update ] do
    member do
      get :assign
    end
  end

  resources :memberships do
    collection do
      get :list
      get :labels
      post :download_labels
      get :spreadsheets
      post :download_spreadsheet
      get :initiation_report
      post :assign_drysail
      post :add_person
    end
    member do
      get :wl
      post :wladd
      get :associate
      patch :save_association
      post :unassign
      post :unassign_drysail
    end
    resources :people
    resources :boats do
      member do
        delete :rmboat
      end
    end
   end

  resources :people, only: [ :destroy ]

  resources :committees, only: [] do
    collection do
      get :select
      get :list
      get :download_all
    end
    member do
      get :download
    end
  end

  resources :boats do
    member do
      get :associate
      patch :save_association
    end
  end

  resources :wait_list_entries, except: [ :show ] do
    member do
      get :assign
      patch :mooring_update
    end
  end

  resources :mailings do
    member do
      post :send_email
    end
  end
  resource :log_info_email, only: [ :edit, :update ]
  get "subscription_list", to: "reports#subscription_list"

  resources :active_sessions, only: [ :index, :destroy ] do
    collection do
      delete "destroy_all"
    end
  end

  get "summary_report", to: "reports#summary"
  get "history_report", to: "reports#history"
  get "moorings_report", to: "reports#moorings"
  get "associates_report", to: "reports#associates"
  get "shrink_image/:id", to: "image#shrink", as: "shrink"
end

app/views/mail_robot/confirmation.html.erb
<p>Thank you for registering with the LCYC administration website.</p>
<p><%= link_to "Click here to confirm your email.", edit_confirmation_url(@confirmation_token) %></p>
<p>- LCYC admin</p>

app/views/mail_robot/confirmation.text.erb
Thank you for registering with the LCYC administration website.

<%= link_to "Click here to confirm your email.", edit_confirmation_url(@confirmation_token) %>

- LCYC admin

app/views/mail_robot/dbbackup.html.erb
<p>Db backup is attached.

app/views/mail_robot/loginfo.html.erb
<p><%= @body %></p>
<p>Note: Children are only listed if they are under 24 years old, see Article
  II, Section 1 (b) of the Bylaws.</p>
<hr/>
<table width="500" class="ms-4">
  <tr>
    <td><bold><%= @membership.LastName %></bold></td>
    <td><bold>Member Since: </bold><%= @membership.MemberSince %></td>
  </tr>
  <tr>
    <td><%= @membership.MailingName %></bold></td>
    <td><bold>Status: </bold><%= @membership.Status %></td>
  </tr>
  <tr>
    <td><%= @membership.StreetAddress %></bold></td>
    <td><bold>Mooring: </bold><%= @membership.mooring&.id %></td>
  </tr>
  <tr>
    <td><%= @membership.City %>, <%= @membership.State %>&nbsp;&nbsp;&nbsp;<%= @membership.Zip %></bold></td>
    <td><bold>Boat Name: </bold><%= @boat[0] %></td>
  </tr>
  <tr>
    <td>Home Phone: <%= @member[0] %></td>
    <td>Type: <%= @boat[1] %></td>
  </tr>
</table>
<hr/>
<table width="500" class="ms-4">
  <tr>
    <th>Name</th>
    <th>Work Phone</th>
    <th>Cell Phone</th>
    <th>Email Address</th>
  </tr>
  <tr>
    <td><%= @member[1] %></td>
    <td><%= @member[2] %></td>
    <td><%= @member[3] %></td>
    <td><%= @member[4] %></td>
  </tr>
  <tr>
    <td><%= @partner[0] %></td>
    <td><%= @partner[1] %></td>
    <td><%= @partner[2] %></td>
    <td><%= @partner[3] %></td>
  </tr>
  <tr>
    <td><%= @children[0] %></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</table>

app/views/mail_robot/password_reset.html.erb
<%= link_to "Click here to reset your password.", edit_password_url(@password_reset_token) %>
<p>This link will expire after 24 hours.</p>
<p>- LCYC admin</p>

app/views/mail_robot/password_reset.text.erb
<%= link_to "Click here to reset your password.", edit_password_url(@password_reset_token) %>
This link will expire after 24 hours.

- LCYC admin