config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "admin#index"

  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"
  get "account", to: "users#edit"
  put "account", to: "users#update"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "change_password", to: "passwords#change"
  post "change_password", to: "passwords#change"


  get "unsubscribe/:id", to: "unsubscribe#show"
  put "unsubscribe/:id", to: "unsubscribe#update"

  mount MissionControl::Jobs::Engine => "/jobs"

  resources :users

  resources :confirmations, only: [ :create, :edit, :new ], param: :confirmation_token
  resources :passwords, only: [ :create, :edit, :new, :update ], param: :password_reset_token

  resource :fee, only: [ :show, :edit, :update ]

  resources :quickbooks do
    collection do
      get :connect             # This starts the OAuth flow
      get :new, as: :callback  # This is where Intuit sends the user back
      get :invoices
      post :generate_invoices
    end
  end

  resources :roles, except: [ :new, :destroy ] do
    resources :users do
      member do
        delete :rmrole
      end
    end
  end

  resources :moorings, only: [ :index ] do
    collection do
      get :unassigned
    end
  end

  resources :drysails, only: [ :index, :update ] do
    member do
      get :assign
    end
  end

  resources :memberships do
    collection do
      get :list
      get :labels
      post :download_labels
      get :spreadsheets
      post :download_spreadsheet
      get :initiation_report
      post :assign_drysail
      post :add_person
    end
    member do
      get :wl
      post :wladd
      get :associate
      patch :save_association
      post :unassign
      post :unassign_drysail
    end
    resources :people
    resources :boats do
      member do
        delete :rmboat
      end
    end
   end

  resources :people, only: [ :destroy ]

  resources :committees, only: [] do
    collection do
      get :select
      get :list
      get :download_all
    end
    member do
      get :download
    end
  end

  resources :boats do
    member do
      get :associate
      patch :save_association
    end
  end

  resources :wait_list_entries, except: [ :show ] do
    member do
      get :assign
      patch :mooring_update
    end
  end

  resources :mailings do
    member do
      post :send_email
    end
  end
  resource :log_info_email, only: [ :edit, :update ]
  get "subscription_list", to: "reports#subscription_list"

  resources :active_sessions, only: [ :index, :destroy ] do
    collection do
      delete "destroy_all"
    end
  end

  get "summary_report", to: "reports#summary"
  get "history_report", to: "reports#history"
  get "moorings_report", to: "reports#moorings"
  get "associates_report", to: "reports#associates"
  get "shrink_image/:id", to: "image#shrink", as: "shrink"
end

app/models/drysail.rb
class Drysail < ApplicationRecord
  belongs_to :membership, optional: true
  has_one :boat

  def self.memberships
    Drysail.select { |e| !e.membership.nil? }.map { |e| e.membership }
  end
end

app/controllers/drysails_controller.rb
class DrysailsController < ApplicationController
  def assign
    @drysail = Drysail.find(params[:id])
    @memberships = Membership.active - Drysail.memberships
  end

  def index
    @drysails = Drysail.order(:id)
  end

  def update
    @drysail = Drysail.find(params[:id])
    @drysail.membership = Membership.find(params[:membership])
    if @drysail.save
      flash[:success] = "Assigned dry sail spot ##{@drysail.id}."
      redirect_to drysails_path
    else
      # :nocov:
      flash.now[:alert] = "Problem assiging dry sail spot"
      render :assign, status: :unprocessable_entity
      # :nocov:
    end
  end
end

app/views/drysails/_drysail.html.erb
<table class="table table-sm table-striped">
  <thead class="thead-light">
    <tr>
      <th>Dry Sail #</th>
      <th>Membership</th>
      <th>Boat Name</th>
      <th>Boat Type</th>
    </tr>
  </thead>
  <tbody>
    <% for drysail in @drysails %>
      <tr scope="row">
	<td><%= drysail.id %></td>
	<% if drysail.membership %>
	  <td><%= link_to drysail.membership&.MailingName, drysail.membership %></td>
	<% else %>
	  <td></td>
	<% end %>
	<% if drysail.boat %>
 	  <td><%= link_to drysail.boat.Name, drysail.boat %></td>
 	  <td><%= link_to drysail.boat.Mfg_Size, drysail.boat %></td>
	<% else %>
	  <td></td>
	  <td></td>
	<% end %>
	<% if drysail.membership %>
	  <td><span class="list-actions"><%= link_to 'Unassign', unassign_drysail_membership_path(drysail.membership),
					  data: {turbo_confirm: 'Are you sure?', turbo_method: :post} %>
	  </span>
	  </td>
	<% else %>
	  <td><span class="list-actions"><%= link_to 'Assign', assign_drysail_path(drysail) %>
	  </td>
	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/drysails/assign.html.erb
<h2><%= "Assigning dry sail spot ##{@drysail.id}" %></h2>

<%= form_with model: @drysail, method: :patch do |f| %>
  <div class="row">
    <label for="Membership" class="col-form-label pt-0">Membership:</label>
    <div class="col-sm-4">
      <%= select_tag :membership, options_from_collection_for_select(@memberships, :id, :MailingName) %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-3 pt-3">
      <%= f.submit "Assign", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/drysails/index.html.erb
<h2>Dry Sailing Storage Assignment</h2>

<p class='small'>To display a boat in this list, change it's location to "Parking Lot" by editing the membership data.</p>

<div id='table'>
  <%= render 'drysail' %>
</div>