config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "admin#index"

  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"
  get "account", to: "users#edit"
  put "account", to: "users#update"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "change_password", to: "passwords#change"
  post "change_password", to: "passwords#change"


  get "unsubscribe/:id", to: "unsubscribe#show"
  put "unsubscribe/:id", to: "unsubscribe#update"

  mount MissionControl::Jobs::Engine => "/jobs"

  resources :users

  resources :confirmations, only: [ :create, :edit, :new ], param: :confirmation_token
  resources :passwords, only: [ :create, :edit, :new, :update ], param: :password_reset_token

  resource :fee, only: [ :show, :edit, :update ]

  resources :quickbooks do
    collection do
      get :connect             # This starts the OAuth flow
      get :new, as: :callback  # This is where Intuit sends the user back
      get :invoices
      post :generate_invoices
    end
  end

  resources :roles, except: [ :new, :destroy ] do
    resources :users do
      member do
        delete :rmrole
      end
    end
  end

  resources :moorings, only: [ :index ] do
    collection do
      get :unassigned
    end
  end

  resources :drysails, only: [ :index, :update ] do
    member do
      get :assign
    end
  end

  resources :memberships do
    collection do
      get :list
      get :labels
      post :download_labels
      get :spreadsheets
      post :download_spreadsheet
      get :initiation_report
      post :assign_drysail
      post :add_person
    end
    member do
      get :wl
      post :wladd
      get :associate
      patch :save_association
      post :unassign
      post :unassign_drysail
    end
    resources :people
    resources :boats do
      member do
        delete :rmboat
      end
    end
   end

  resources :people, only: [ :destroy ]

  resources :committees, only: [] do
    collection do
      get :select
      get :list
      get :download_all
    end
    member do
      get :download
    end
  end

  resources :boats do
    member do
      get :associate
      patch :save_association
    end
  end

  resources :wait_list_entries, except: [ :show ] do
    member do
      get :assign
      patch :mooring_update
    end
  end

  resources :mailings do
    member do
      post :send_email
    end
  end
  resource :log_info_email, only: [ :edit, :update ]
  get "subscription_list", to: "reports#subscription_list"

  resources :active_sessions, only: [ :index, :destroy ] do
    collection do
      delete "destroy_all"
    end
  end

  get "summary_report", to: "reports#summary"
  get "history_report", to: "reports#history"
  get "moorings_report", to: "reports#moorings"
  get "associates_report", to: "reports#associates"
  get "shrink_image/:id", to: "image#shrink", as: "shrink"
end

app/models/committee.rb
class Committee < ApplicationRecord
  has_many :people

  def self.names
    Committee.order(:Name).map { |c| c.Name }
  end
end

app/controllers/committees_controller.rb
class CommitteesController < ApplicationController
  def select; end

  def list
    if params[:committee] == "All"
      @committee = "All"
      @people = Person.active.where(MemberType: %w[Member Partner]).order(:LastName)
    else
      @committee = params[:committee] || "Boats"
      @people = Person.active.where(MemberType: %w[Member Partner]).committee(@committee).order(:LastName)
    end
  end

  def download_all
    @people = Person.active.where(MemberType: %w[Member Partner]).order(:LastName)
    content = Person.committee_spreadsheet(@people)
    send_data(content, type: "text/csv", filename: "All_committees.csv")
  end

  def download
    @committee = params[:id]
    @people = Person.active.where(MemberType: %w[Member Partner]).committee(@committee).order(:LastName)
    content = Person.committee_spreadsheet(@people)
    send_data(content, type: "text/csv", filename: "#{params[:id]}_committee.csv")
  end
end

app/views/committees/_committee_list.html.erb
<p class="mt-3">Total members: <%= @people.length %></p>
<table class="table table-sm table-striped">
  <thead class="thead-light">
    <tr>
      <th>Last Name</th>
      <th>First Name</th>
      <th>Home Phone</th>
      <th>Work Phone</th>
      <th>Cell Phone</th>
      <th>Email</th>
      <th>Committee</th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |p| %>
    <tr scope="row" %>
      <td><%= p.LastName %></td>
      <td><%= p.FirstName %></td>
      <td><%= p.HomePhone %></td>
      <td><%= p.WorkPhone %></td>
      <td><%= p.CellPhone %></td>
      <td><%= p.EmailAddress %></td>
      <td><%= p.Committee1 %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/committees/list.html.erb
<% if @committee == "All" %>
  <h2 class="mt-3 mb-3">Committee listing for all members</h2>
  <div>
    <%= form_with url: download_all_committees_path(@committee), method: :get, data: { turbo: false} do |f| %>
      <%= f.submit "Download as a spreadsheet", class: "btn btn-primary" %> | <%= link_to 'Back', select_committees_path %>
    <% end %>
  </div>
<% else %>
  <h2 class="mt-3 mb-3"><%= @committee %> Committee</h2>
  <div>
    <%= form_with url: download_committee_path(@committee), method: :get, data: { turbo: false} do |f| %>
      <%= f.submit "Download as a spreadsheet", class: "btn btn-primary" %> | <%= link_to 'Back', select_committees_path %>
    <% end %>
  </div>
<% end %>
<%= render 'committee_list' %>

app/views/committees/select.html.erb
<h2 class="mb-3">Committee Members</h2>
<div>
  <%= form_with url: list_committees_path, method: :get do |f| %>
    <%= select_tag :committee, options_for_select(["All"].concat(Committee.names), @committee) %>
    <%= f.submit "Show", class: "btn btn-primary" %>
  <% end %>
</div>